import React from 'react';
import { motion } from 'motion/react';
import { Link } from 'react-router-dom';
import { 
  Pill, 
  MapPin, 
  Truck, 
  Clock, 
  ShieldCheck, 
  TrendingUp, 
  FileCheck, 
  ArrowRight, 
  Sparkles,
  ShoppingBag,
  Store,
  Layers
} from 'lucide-react';
import { SEO } from '../components/common/SEO';

export const ForPharmaciesPage: React.FC = () => {
  const benefits = [
    {
      title: 'Digital Pharmacy Storefront',
      desc: 'Gain instant digital visibility among patients in your neighborhood actively searching for prescription and OTC medications.',
      icon: Store
    },
    {
      title: 'Digital Prescription Orders',
      desc: 'Receive clear, legible digital prescriptions generated by verified doctors, eliminating handwriting errors and dispensing ambiguities.',
      icon: ShoppingBag
    },
    {
      title: 'Configurable Delivery Zones',
      desc: 'Define your exact delivery radius, minimum order thresholds, home delivery availability, and 24/7 operating hours.',
      icon: Truck
    },
    {
      title: 'Real-Time Inventory Management',
      desc: 'Manage stock levels, price discounts, and out-of-stock alerts for essential medications across critical healthcare categories.',
      icon: Layers
    },
    {
      title: 'State Drug License Verification',
      desc: 'Stand out with the official MediTrust Verified Pharmacy badge by validating your Form 20/21 state drug licenses.',
      icon: ShieldCheck
    },
    {
      title: 'Neighborhood Customer Loyalty',
      desc: 'Build recurring customer relationships for chronic illness medications like diabetes, hypertension, and cardiac care.',
      icon: TrendingUp
    }
  ];

  return (
    <div className="min-h-screen bg-[#F7F8F6] text-[#101515] py-12 px-4 sm:px-6 lg:px-8">
      <SEO 
        title="For Pharmacies | Expand Your Pharmacy's Digital Reach with MediTrust"
        description="Onboard your licensed pharmacy to MediTrust. Accept digital prescription orders, manage inventory, and deliver medicines to nearby patients."
        keywords={['pharmacy onboarding', 'digital pharmacy dispensary', 'MediTrust pharmacy network', 'medicine delivery India']}
        canonicalUrl="https://medynex.com/for-pharmacies"
      />

      <div className="max-w-7xl mx-auto space-y-16">
        
        {/* Hero Section */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-10 items-center">
          <div className="lg:col-span-7 space-y-6">
            <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-[#EAF5F1] border border-[#DCEFEA] text-[#0E6763] text-xs font-semibold">
              <Sparkles className="w-3.5 h-3.5" />
              <span>Licensed Pharmacy Network</span>
            </div>

            <h1 className="text-4xl sm:text-5xl lg:text-6xl font-extrabold text-[#101515] tracking-tight leading-[1.1]">
              Make your pharmacy <br />
              <span className="text-[#0E6763]">easier to discover.</span>
            </h1>

            <p className="text-base sm:text-lg text-[#737A78] max-w-xl leading-relaxed">
              Connect with patients searching for genuine medicines, accept verified digital prescriptions from registered doctors, and expand your delivery radius with MediTrust.
            </p>

            <div className="flex flex-wrap items-center gap-4 pt-2">
              <Link
                to="/register?role=pharmacy"
                className="px-7 py-3.5 rounded-2xl bg-[#101515] hover:bg-[#0E6763] text-white font-bold text-sm transition-all shadow-xl hover:-translate-y-0.5 flex items-center gap-2"
              >
                <Pill className="w-4 h-4" />
                <span>Join as a Pharmacy</span>
                <ArrowRight className="w-4 h-4" />
              </Link>
              <Link
                to="/how-it-works"
                className="px-6 py-3.5 rounded-2xl bg-white text-[#101515] border border-[#E7EAE7] hover:border-[#0E6763] font-semibold text-sm transition-all"
              >
                <span>Learn How It Works</span>
              </Link>
            </div>

            <div className="grid grid-cols-3 gap-4 pt-4 border-t border-[#E7EAE7]/80">
              <div>
                <div className="text-2xl font-black text-[#101515]">100%</div>
                <div className="text-xs text-[#737A78]">Licensed Chemist Stores</div>
              </div>
              <div>
                <div className="text-2xl font-black text-[#101515]">15 km</div>
                <div className="text-xs text-[#737A78]">Target Delivery Radius</div>
              </div>
              <div>
                <div className="text-2xl font-black text-[#101515]">Direct</div>
                <div className="text-xs text-[#737A78]">Prescription Fulfillment</div>
              </div>
            </div>
          </div>

          <div className="lg:col-span-5">
            <div className="card-editorial p-8 bg-white border border-[#E7EAE7] shadow-xl space-y-6 relative overflow-hidden">
              <div className="space-y-2">
                <span className="text-xs font-bold text-[#0E6763] uppercase tracking-wider">Verification Standards</span>
                <h3 className="text-2xl font-bold text-[#101515]">Pharmacy Onboarding Process</h3>
                <p className="text-xs text-[#737A78]">Transparent compliance verification protecting patient safety.</p>
              </div>

              <div className="space-y-4">
                {[
                  { step: '1', title: 'Business Profile', desc: 'Provide pharmacy trade name, store address, and contact numbers.' },
                  { step: '2', title: 'Drug License Audit', desc: 'Submit state drug license (Form 20/21) and GST registration numbers.' },
                  { step: '3', title: 'Delivery & Hours Config', desc: 'Set your operating hours (24/7 or custom) and local dispatch radius.' },
                  { step: '4', title: 'Go Live & Accept Orders', desc: 'Once approved by admin, nearby patients can discover and order medications.' }
                ].map((item) => (
                  <div key={item.step} className="flex items-start gap-3.5 p-3 rounded-xl bg-[#F7F8F6] border border-[#E7EAE7]/60">
                    <span className="w-7 h-7 rounded-full bg-[#101515] text-white text-xs font-bold flex items-center justify-center shrink-0">
                      {item.step}
                    </span>
                    <div>
                      <h4 className="text-sm font-bold text-[#101515]">{item.title}</h4>
                      <p className="text-xs text-[#737A78]">{item.desc}</p>
                    </div>
                  </div>
                ))}
              </div>

              <Link
                to="/register?role=pharmacy"
                className="w-full py-3 rounded-xl bg-[#0E6763] hover:bg-[#2B9A91] text-white text-xs font-bold transition-all shadow-md flex items-center justify-center gap-2"
              >
                <span>Start Pharmacy Registration</span>
                <ArrowRight className="w-3.5 h-3.5" />
              </Link>
            </div>
          </div>
        </div>

        {/* Benefits Grid */}
        <div className="space-y-8">
          <div className="text-center max-w-2xl mx-auto space-y-3">
            <h2 className="text-3xl font-extrabold text-[#101515]">Advantages for Licensed Pharmacies</h2>
            <p className="text-sm text-[#737A78]">
              Designed to help independent pharmacies and retail pharmacy chains modernize their operations and customer acquisition.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {benefits.map((b, idx) => {
              const Icon = b.icon;
              return (
                <div key={idx} className="card-editorial p-7 bg-white space-y-4">
                  <div className="w-12 h-12 rounded-2xl bg-[#EAF5F1] text-[#0E6763] flex items-center justify-center border border-[#DCEFEA]">
                    <Icon className="w-6 h-6" />
                  </div>
                  <h3 className="text-lg font-bold text-[#101515]">{b.title}</h3>
                  <p className="text-xs sm:text-sm text-[#737A78] leading-relaxed">
                    {b.desc}
                  </p>
                </div>
              );
            })}
          </div>
        </div>

        {/* Pharmacy CTA Banner */}
        <div className="card-editorial p-8 sm:p-12 bg-[#101515] text-white rounded-[2.5rem] flex flex-col md:flex-row items-center justify-between gap-8">
          <div className="space-y-3 text-center md:text-left max-w-2xl">
            <h3 className="text-2xl sm:text-3xl font-extrabold text-white">Bring your pharmacy into the digital health era</h3>
            <p className="text-sm text-slate-300">
              Join MediTrust today and start receiving digital prescription orders directly from patients and doctors in your city.
            </p>
          </div>
          <Link
            to="/register?role=pharmacy"
            className="px-8 py-4 rounded-2xl bg-[#0E6763] hover:bg-[#2B9A91] text-white font-bold text-sm transition-all shadow-xl shrink-0 flex items-center gap-2"
          >
            <Pill className="w-4 h-4" />
            <span>Register as a Pharmacy</span>
          </Link>
        </div>

      </div>
    </div>
  );
};
