import React, { createContext, useContext, useState, useEffect } from 'react';
import { SupportedLanguage } from '../types';

export interface LanguageInfo {
  code: SupportedLanguage;
  name: string;
  nativeName: string;
}

export const SUPPORTED_LANGUAGES: LanguageInfo[] = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' },
];

const TRANSLATIONS: Record<SupportedLanguage, Record<string, string>> = {
  en: {
    findDoctors: 'Find Doctors',
    findHospitals: 'Find Hospitals',
    findPharmacies: 'Find Pharmacies',
    findLabs: 'Find Laboratories',
    searchPlaceholder: 'Search by doctor name, specialty, hospital, pharmacy or medicine...',
    locationLabel: 'Your Location',
    changeLocation: 'Change Location',
    selectLanguage: 'Select Language',
    requestDoctor: 'Request this Doctor',
    requestPharmacy: 'Request this Pharmacy',
    requestLab: 'Request this Laboratory',
    bookAppointment: 'Book OPD Appointment',
    videoConsult: 'Video Consult',
    orderMedicines: 'Order Medicines',
    bookTest: 'Book Lab Test',
    activeOnMediTrust: 'Active on MediTrust',
    notYetOnboarded: 'Not Yet Onboarded',
    verificationPending: 'Verification Pending',
    requestCount: 'patient requests',
    rating: 'Rating',
    distance: 'away',
    consultationFee: 'Fee',
    emergency24x7: '24x7 Emergency',
    viewDetails: 'View Details',
    notifications: 'Notifications',
    noNotifications: 'No new notifications',
    requestedProviderOnboarded: 'Requested Provider Joined!',
    bookNow: 'Book Now',
    languageUpdated: 'Language updated successfully',
    locationUpdated: 'Location updated successfully',
  },
  hi: {
    findDoctors: 'डॉक्टर खोजें',
    findHospitals: 'अस्पताल खोजें',
    findPharmacies: 'मेडिकल स्टोर खोजें',
    findLabs: 'पैथोलॉजी लैब खोजें',
    searchPlaceholder: 'डॉक्टर, विशेषता, अस्पताल या दवा के नाम से खोजें...',
    locationLabel: 'आपका स्थान',
    changeLocation: 'स्थान बदलें',
    selectLanguage: 'भाषा चुनें',
    requestDoctor: 'इस डॉक्टर का अनुरोध करें',
    requestPharmacy: 'इस मेडिकल स्टोर का अनुरोध करें',
    requestLab: 'इस लैब का अनुरोध करें',
    bookAppointment: 'ओपीडी अपॉइंटमेंट बुक करें',
    videoConsult: 'वीडियो परामर्श',
    orderMedicines: 'दवाइयां ऑर्डर करें',
    bookTest: 'लैब टेस्ट बुक करें',
    activeOnMediTrust: 'मेडीट्रस्ट पर सक्रिय',
    notYetOnboarded: 'अभी पंजीकृत नहीं',
    verificationPending: 'सत्यापन लंबित',
    requestCount: 'मरीजों के अनुरोध',
    rating: 'रेटिंग',
    distance: 'दूरी',
    consultationFee: 'शुल्क',
    emergency24x7: '24x7 आपातकालीन सेवा',
    viewDetails: 'विवरण देखें',
    notifications: 'सूचनाएं',
    noNotifications: 'कोई नई सूचना नहीं',
    requestedProviderOnboarded: 'अनुरोधित डॉक्टर मेडीट्रस्ट से जुड़े!',
    bookNow: 'अभी बुक करें',
    languageUpdated: 'भाषा सफलतापूर्वक अद्यतन की गई',
    locationUpdated: 'स्थान सफलतापूर्वक अद्यतन किया गया',
  },
  te: {
    findDoctors: 'వైద్యులను శోధించండి',
    findHospitals: 'ఆసుపత్రులను శోధించండి',
    findPharmacies: 'మందుల షాపులు',
    findLabs: 'ల్యాబ్‌లు',
    searchPlaceholder: 'డాక్టర్ పేరు, స్పెషాలిటీ, ఆసుపత్రి లేదా మందుల కోసం వెతకండి...',
    locationLabel: 'మీ ప్రాంతం',
    changeLocation: 'ప్రాంతం మార్చండి',
    selectLanguage: 'భాషను ఎంచుకోండి',
    requestDoctor: 'ఈ డాక్టర్‌ని అభ్యర్థించండి',
    requestPharmacy: 'ఈ మెడికల్ షాపును అభ్యర్థించండి',
    requestLab: 'ఈ ల్యాబ్‌ని అభ్యర్థించండి',
    bookAppointment: 'అపాయింట్‌మెంట్ బుక్ చేయండి',
    videoConsult: 'వీడియో సంప్రదింపు',
    orderMedicines: 'మందులు ఆర్డర్ చేయండి',
    bookTest: 'ల్యాబ్ టెస్ట్ బుక్ చేయండి',
    activeOnMediTrust: 'మెడిట్రస్ట్‌లో యాక్టివ్‌గా ఉన్నారు',
    notYetOnboarded: 'ఇంకా రిజిస్టర్ కాలేదు',
    verificationPending: 'పరిశీలనలో ఉంది',
    requestCount: 'రోగుల అభ్యర్థనలు',
    rating: 'రేటింగ్',
    distance: 'దూరం',
    consultationFee: 'ఫీజు',
    emergency24x7: '24x7 అత్యవసర సేవలు',
    viewDetails: 'వివరాలు చూడండి',
    notifications: 'నోటిఫికేషన్లు',
    noNotifications: 'కొత్త నోటిఫికేషన్‌లు లేవు',
    requestedProviderOnboarded: 'మీరు కోరిన డాక్టర్ మెడిట్రస్ట్‌లో చేరారు!',
    bookNow: 'ఇప్పుడే బుక్ చేయండి',
    languageUpdated: 'భాష విజయవంతంగా మార్చబడింది',
    locationUpdated: 'ప్రాంతం విజయవంతంగా మార్చబడింది',
  },
  ta: {
    findDoctors: 'மருத்துவர்களை தேடுங்கள்',
    findHospitals: 'மருத்துவமனைகள்',
    findPharmacies: 'மருந்தகங்கள்',
    findLabs: 'பரிசோதனை நிலையங்கள்',
    searchPlaceholder: 'மருத்துவர், சிறப்பு, மருத்துவமனை அல்லது மருந்து தேடுக...',
    locationLabel: 'உங்கள் இருப்பிடம்',
    changeLocation: 'இருப்பிடம் மாற்றுக',
    selectLanguage: 'மொழியைத் தேர்ந்தெடுக்கவும்',
    requestDoctor: 'இந்த மருத்துவரை கோருங்கள்',
    requestPharmacy: 'இந்த மருந்தகத்தை கோருங்கள்',
    requestLab: 'இந்த ஆய்வகத்தை கோருங்கள்',
    bookAppointment: 'நேரடி முன்பதிவு செய்க',
    videoConsult: 'வீடியோ ஆலோசனைக் கட்டணம்',
    orderMedicines: 'மருந்துகள் ஆர்டர் செய்க',
    bookTest: 'பரிசோதனை முன்பதிவு செய்க',
    activeOnMediTrust: 'மெடிட்ரஸ்ட்டில் செயலில் உள்ளது',
    notYetOnboarded: 'இன்னும் இணையவில்லை',
    verificationPending: 'சரிபார்ப்பு நிலுவையில் ఉంది',
    requestCount: 'நோயாளி கோரிக்கைகள்',
    rating: 'மதிப்பீடு',
    distance: 'தூரம்',
    consultationFee: 'கட்டணம்',
    emergency24x7: '24x7 அவசர சேவை',
    viewDetails: 'விவரங்களை பார்க்க',
    notifications: 'அறிவிப்புகள்',
    noNotifications: 'புதிய அறிவிப்புகள் இல்லை',
    requestedProviderOnboarded: 'நீங்கள் கேட்ட மருத்துவர் இணைந்தார்!',
    bookNow: 'இப்போதே முன்பதிவு செய்க',
    languageUpdated: 'மொழி புதுப்பிக்கப்பட்டது',
    locationUpdated: 'இருப்பிடம் புதுப்பிக்கப்பட்டது',
  },
  kn: {
    findDoctors: 'ವೈದ್ಯರನ್ನು ಹುಡುಕಿ',
    findHospitals: 'ಆಸ್ಪತ್ರೆಗಳು',
    findPharmacies: 'ಫಾರ್ಮಸಿಗಳು',
    findLabs: 'ಲ್ಯಾಬ್‌ಗಳು',
    searchPlaceholder: 'ವೈದ್ಯರು, ಆಸ್ಪತ್ರೆ ಅಥವಾ ಔಷಧಿಯ ಹೆಸರಿನಿಂದ ಹುಡುಕಿ...',
    locationLabel: 'ನಿಮ್ಮ ಸ್ಥಳ',
    changeLocation: 'ಸ್ಥಳ ಬದಲಾಯಿಸಿ',
    selectLanguage: 'ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ',
    requestDoctor: 'ಈ ವೈದ್ಯರನ್ನು ವಿನಂತಿಸಿ',
    requestPharmacy: 'ಈ ಫಾರ್ಮಸಿಯನ್ನು ವಿನಂತಿಸಿ',
    requestLab: 'ಈ ಲ್ಯಾಬ್ ವಿನಂತಿಸಿ',
    bookAppointment: 'ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ಕಾಯ್ದಿರಿಸಿ',
    videoConsult: 'ವೀಡಿಯೊ ಸಮಾಲೋಚನೆ',
    orderMedicines: 'ಔಷಧಿಗಳನ್ನು ಆರ್ಡರ್ ಮಾಡಿ',
    bookTest: 'ಲ್ಯಾಬ್ ಪರೀಕ್ಷೆ ಕಾಯ್ದಿರಿಸಿ',
    activeOnMediTrust: 'ಮೆಡಿಟ್ರಸ್ಟ್‌ನಲ್ಲಿ ಸಕ್ರಿಯವಾಗಿದೆ',
    notYetOnboarded: 'ಇನ್ನೂ ನೋಂದಾಯಿಸಲಾಗಿಲ್ಲ',
    verificationPending: 'ಪರಿಶೀಲನೆ ಬಾಕಿ ಇದೆ',
    requestCount: 'ರೋಗಿಗಳ ವಿನಂತಿಗಳು',
    rating: 'ರೇಟಿಂಗ್',
    distance: 'ದೂರ',
    consultationFee: 'ಶುಲ್ಕ',
    emergency24x7: '24x7 ತುರ್ತು ಸೇವೆ',
    viewDetails: 'ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
    notifications: 'ಅಧಿಸೂಚನೆಗಳು',
    noNotifications: 'ಯಾವುದೇ ಹೊಸ ಅಧಿಸೂಚನೆಗಳಿಲ್ಲ',
    requestedProviderOnboarded: 'ನೀವು ಕೋರಿದ ವೈದ್ಯರು ಸೇರಿದ್ಧಾರೆ!',
    bookNow: 'ಈಗಲೇ ಕಾಯ್ದಿರಿಸಿ',
    languageUpdated: 'ಭಾಷೆಯನ್ನು ಯಶಸ್ವಿಯಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ',
    locationUpdated: 'ಸ್ಥಳವನ್ನು ಯಶಸ್ವಿಯಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ',
  },
  ml: {
    findDoctors: 'ഡോക്ടർമാരെ കണ്ടെത്തുക',
    findHospitals: 'ആശുപത്രികൾ',
    findPharmacies: 'ഫാർമസികൾ',
    findLabs: 'ലാബുകൾ',
    searchPlaceholder: 'ഡോക്ടറുടെ പേര്, സ്പെഷ്യാലിറ്റി, മരുന്ന് തിരയുക...',
    locationLabel: 'നിങ്ങളുടെ സ്ഥലം',
    changeLocation: 'സ്ഥലം മാറ്റുക',
    selectLanguage: 'ഭാഷ തിരഞ്ഞെടുക്കുക',
    requestDoctor: 'ഈ ഡോക്ടറെ അഭ്യർത്ഥിക്കുക',
    requestPharmacy: 'ഈ ഫാർമസി അഭ്യർത്ഥിക്കുക',
    requestLab: 'ഈ ലാബ് അഭ്യർത്ഥിക്കുക',
    bookAppointment: 'അപ്പോയിന്റ്മെന്റ് ബുക്ക് ചെയ്യുക',
    videoConsult: 'വീഡിയോ കൺസൾട്ടേഷൻ',
    orderMedicines: 'മരുന്നുകൾ ഓർഡർ ചെയ്യുക',
    bookTest: 'ലാബ് ടെസ്റ്റ് ബുക്ക് ചെയ്യുക',
    activeOnMediTrust: 'മെഡിട്രസ്റ്റിൽ ലഭ്യമാണ്',
    notYetOnboarded: 'ഇതുവരെ രജിസ്റ്റർ ചെയ്തിട്ടില്ല',
    verificationPending: 'പരിശോധനയിലാണ്',
    requestCount: 'രോഗികളുടെ അഭ്യർത്ഥനകൾ',
    rating: 'റേറ്റിംഗ്',
    distance: 'ദൂരം',
    consultationFee: 'ഫീസ്',
    emergency24x7: '24x7 അടിയന്തര സേവനം',
    viewDetails: 'വിശദാംശങ്ങൾ കാണുക',
    notifications: 'അറിയിപ്പുകൾ',
    noNotifications: 'പുതിയ അറിയിപ്പുകളൊന്നുമില്ല',
    requestedProviderOnboarded: 'നിങ്ങൾ അഭ്യർത്ഥിച്ച ഡോക്ടർ മെഡിട്രസ്റ്റിൽ ചേർന്നു!',
    bookNow: 'ഇപ്പോൾ ബുക്ക് ചെയ്യുക',
    languageUpdated: 'ഭാഷ വിജയകരമായി മാറ്റി',
    locationUpdated: 'സ്ഥലം വിജയകരമായി മാറ്റി',
  },
  bn: {
    findDoctors: 'ডাক্তার খুঁজুন',
    findHospitals: 'হাসপাতাল খুঁজুন',
    findPharmacies: 'ফার্মেসি খুঁজুন',
    findLabs: 'ডায়াগনস্টিক ল্যাব',
    searchPlaceholder: 'ডাক্তার, হাসপাতাল বা ওষুধের নাম দিয়ে খুঁজুন...',
    locationLabel: 'আপনার অবস্থান',
    changeLocation: 'অবস্থান পরিবর্তন করুন',
    selectLanguage: 'ভাষা নির্বাচন করুন',
    requestDoctor: 'এই ডাক্তারকে অনুরোধ করুন',
    requestPharmacy: 'এই ফার্মেসি অনুরোধ করুন',
    requestLab: 'এই ল্যাব অনুরোধ করুন',
    bookAppointment: 'অ্যাপয়েন্টমেন্ট বুক করুন',
    videoConsult: 'ভিডিও পরামর্শ',
    orderMedicines: 'ওষুধ অর্ডার করুন',
    bookTest: 'ল্যাব টেস্ট বুক করুন',
    activeOnMediTrust: 'মেডিট্রাস্টে সক্রিয়',
    notYetOnboarded: 'এখনও নিবন্ধিত নয়',
    verificationPending: 'যাচাইকরণ বাকি',
    requestCount: 'রোগীর অনুরোধ',
    rating: 'রেটিং',
    distance: 'দূরত্ব',
    consultationFee: 'ফি',
    emergency24x7: '২৪x৭ জরুরি সেবা',
    viewDetails: 'বিস্তারিত দেখুন',
    notifications: 'বিজ্ঞপ্তি',
    noNotifications: 'কোনো নতুন বিজ্ঞপ্তি নেই',
    requestedProviderOnboarded: 'আপনার অনুরোধ করা ডাক্তার যুক্ত হয়েছেন!',
    bookNow: 'এখনই বুক করুন',
    languageUpdated: 'ভাষা সফলভাবে আপডেট করা হয়েছে',
    locationUpdated: 'অবস্থান সফলভাবে আপডেট করা হয়েছে',
  },
  mr: {
    findDoctors: 'डॉक्टर शोधा',
    findHospitals: 'रुग्णालये शोधा',
    findPharmacies: 'औषध दुकाने',
    findLabs: 'लॅब शोधा',
    searchPlaceholder: 'डॉक्टर, रुग्णालय किंवा औषधाचे नाव शोधा...',
    locationLabel: 'तुमचे स्थान',
    changeLocation: 'स्थान बदला',
    selectLanguage: 'भाषा निवडा',
    requestDoctor: 'या डॉक्टरांची विनंती करा',
    requestPharmacy: 'या औषध दुकानाची विनंती करा',
    requestLab: 'या लॅबची विनंती करा',
    bookAppointment: 'अपॉइंटमेंट बुक करा',
    videoConsult: 'व्हिडिओ सल्ला',
    orderMedicines: 'औषधे ऑर्डर करा',
    bookTest: 'लॅब टेस्ट बुक करा',
    activeOnMediTrust: 'मेडीट्रस्टवर सक्रिय',
    notYetOnboarded: 'अजून नोंदणीकृत नाही',
    verificationPending: 'तपासणी प्रलंबित',
    requestCount: 'रुग्णांच्या विनंत्या',
    rating: 'रेटिंग',
    distance: 'अंतर',
    consultationFee: 'फी',
    emergency24x7: '24x7 आपत्कालीन सेवा',
    viewDetails: 'तपशील पहा',
    notifications: 'सूचना',
    noNotifications: 'नवीन सूचना नाहीत',
    requestedProviderOnboarded: 'तुम्ही विनंती केलेले डॉक्टर मेडीट्रस्टवर सामील झाले!',
    bookNow: 'आत्ताच बुक करा',
    languageUpdated: 'भाषा यशस्वीरीत्या अद्यतनित केली',
    locationUpdated: 'स्थान यशस्वीरीत्या अद्यतनित केले',
  },
  gu: {
    findDoctors: 'ડૉક્ટર શોધો',
    findHospitals: 'હોસ્પિટલ શોધો',
    findPharmacies: 'મેડિકલ સ્ટોર',
    findLabs: 'લેબોરેટરી',
    searchPlaceholder: 'ડૉક્ટર, સ્પેશિયાલિટી અથવા દવાનું નામ શોધો...',
    locationLabel: 'તમારું સ્થળ',
    changeLocation: 'સ્થળ બદલો',
    selectLanguage: 'ભાષા પસંદ કરો',
    requestDoctor: 'આ ડૉક્ટરની વિનંતી કરો',
    requestPharmacy: 'આ મેડિકલ સ્ટોરની વિનંતી કરો',
    requestLab: 'આ લેબની વિનંતી કરો',
    bookAppointment: 'એપોઇન્ટમેન્ટ બુક કરો',
    videoConsult: 'વિડિઓ પરામર્શ',
    orderMedicines: 'દવાઓ ઓર્ડર કરો',
    bookTest: 'લેબ ટેસ્ટ બુક કરો',
    activeOnMediTrust: 'મેડીટ્રસ્ટ પર સક્રિય',
    notYetOnboarded: 'હજુ રજિસ્ટર્ડ નથી',
    verificationPending: 'ચકાસણી બાકી',
    requestCount: 'દર્દીઓની વિનંતીઓ',
    rating: 'રેટિંગ',
    distance: 'અંતર',
    consultationFee: 'ફી',
    emergency24x7: '24x7 કટોકટી સેવા',
    viewDetails: 'વિગતો જુઓ',
    notifications: 'સૂચનાઓ',
    noNotifications: 'કોઈ નવી સૂચનાઓ નથી',
    requestedProviderOnboarded: 'તમે વિનંતી કરેલ ડૉક્ટર મેડીટ્રસ્ટ પર જોડાયા!',
    bookNow: 'હમણાં બુક કરો',
    languageUpdated: 'ભાષા સફળતાપૂર્વક અપડેટ થઈ',
    locationUpdated: 'સ્થળ સફળતાપૂર્વક અપડેટ થયું',
  },
  pa: {
    findDoctors: 'ਡਾਕਟਰ ਲੱਭੋ',
    findHospitals: 'ਹਸਪਤਾਲ ਲੱਭੋ',
    findPharmacies: 'ਮੈਡੀਕਲ ਸਟੋਰ',
    findLabs: 'ਲੈਬਾਰਟਰੀ ਲੱਭੋ',
    searchPlaceholder: 'ਡਾਕਟਰ, ਹਸਪਤਾਲ ਜਾਂ ਦਵਾਈ ਦਾ ਨਾਮ ਲੱਭੋ...',
    locationLabel: 'ਤੁਹਾਡਾ ਇਲਾਕਾ',
    changeLocation: 'ਇਲਾਕਾ ਬਦਲੋ',
    selectLanguage: 'ਭਾਸ਼ਾ ਚੁਣੋ',
    requestDoctor: 'ਇਸ ਡਾਕਟਰ ਦੀ ਬੇਨਤੀ ਕਰੋ',
    requestPharmacy: 'ਇਸ ਮੈਡੀਕਲ ਸਟੋਰ ਦੀ ਬੇਨਤੀ ਕਰੋ',
    requestLab: 'ਇਸ ਲੈਬ ਦੀ ਬੇਨਤੀ ਕਰੋ',
    bookAppointment: 'ਅਪਾਇੰਟਮੈਂਟ ਬੁੱਕ ਕਰੋ',
    videoConsult: 'ਵੀਡੀਓ ਸਲਾਹ',
    orderMedicines: 'ਦਵਾਈਆਂ ਆਰਡਰ ਕਰੋ',
    bookTest: 'ਲੈਬ ਟੈਸਟ ਬੁੱਕ ਕਰੋ',
    activeOnMediTrust: 'ਮੈਡੀਟਰੱਸਟ \'ਤੇ ਐਕਟਿਵ',
    notYetOnboarded: 'ਅਜੇ ਰਜਿਸਟਰਡ ਨਹੀਂ',
    verificationPending: 'ਜਾਂਚ ਲੰਬਿਤ',
    requestCount: 'ਮਰੀਜ਼ਾਂ ਦੀਆਂ ਬੇਨਤੀਆਂ',
    rating: 'ਰੇਟਿੰਗ',
    distance: 'ਦੂਰੀ',
    consultationFee: 'ਫੀਸ',
    emergency24x7: '24x7 ਐਮਰਜੈਂਸੀ',
    viewDetails: 'ਵੇਰਵੇ ਵੇਖੋ',
    notifications: 'ਨੋਟੀਫਿਕੇਸ਼ਨ',
    noNotifications: 'ਕੋਈ ਨਵਾਂ ਨੋਟੀਫਿਕੇਸ਼ਨ ਨਹੀਂ',
    requestedProviderOnboarded: 'ਤੁਹਾਡੇ ਵਲੋਂ ਮੰਗੇ ਗਏ ਡਾਕਟਰ ਮੈਡੀਟਰੱਸਟ ਨਾਲ ਜੁੜ ਗਏ!',
    bookNow: 'ਹੁਣੇ ਬੁੱਕ ਕਰੋ',
    languageUpdated: 'ਭਾਸ਼ਾ ਸਫਲਤਾਪੂਰਵਕ ਬਦਲੀ ਗਈ',
    locationUpdated: 'ਇਲਾਕਾ ਸਫਲਤਾਪੂਰਵਕ ਬਦਲਿਆ ਗਿਆ',
  }
};

interface LanguageContextType {
  language: SupportedLanguage;
  setLanguage: (lang: SupportedLanguage) => void;
  t: (key: string, fallback?: string) => string;
  languages: LanguageInfo[];
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<SupportedLanguage>(() => {
    const saved = localStorage.getItem('meditrust_lang') as SupportedLanguage;
    return saved && TRANSLATIONS[saved] ? saved : 'en';
  });

  const setLanguage = (lang: SupportedLanguage) => {
    setLanguageState(lang);
    localStorage.setItem('meditrust_lang', lang);
  };

  const t = (key: string, fallback?: string): string => {
    const langDict = TRANSLATIONS[language] || TRANSLATIONS.en;
    if (langDict[key]) return langDict[key];
    if (TRANSLATIONS.en[key]) return TRANSLATIONS.en[key];
    return fallback || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, languages: SUPPORTED_LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
